### ISSUE TITLE
[Bug] Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by vasiliy-andreychikov-wmg** [getbigger-io/prisma-fixtures#2]
### Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| typeorm-fixtures | 1.0.9
| Node             |16.2.0
| npm/Yarn         |7.13.0
| Operating System |MacOs

When connected field is optional and field defined as connectedFields: ['timezone'] but it not set in some fixtures - it fails.

**Comment by vasiliy-andreychikov-wmg** [comment]
e.g.
```yml
entity: user
connectedFields: ['timezone']
items:
  user1:
    firstName: 'System'
    timezone: '@timezone*'
  user2:
    firstName: 'System'
```
and in schema:
```prisma
model User {
  id             Int          @id @default(autoincrement())
  timezone       Timezone?    @relation(fields: [timezoneId], references: [id])
  timezoneId     Int?
}
```
